import { NavbarDemo } from "@/components/global/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from '@/Providers/NextAuthProvider';
import Footer from '@/components/global/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Md Abdul Kyum",
  description: "Generated by Md Abdul Kyum",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
           <NavbarDemo></NavbarDemo>
         
               <main className="">{children}</main>
            
           <Footer></Footer>
        </NextAuthProvider>
      </body>
    </html>
  );
}
